# Generated by Django 3.2.24 on 2024-02-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_voetbalspelers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voetbalspelers',
            name='Naam_voetballer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voetbalspelers',
            name='actuele_voetbalclub',
            field=models.CharField(max_length=100),
        ),
    ]
